config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :localities
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/relacion/:nombre/:localities_id', to: "localities#relacion"
  get '/newticket/:event_id', to: "tickets#newticket"
  get '/updateticket/:id_ticket/:event_id/', to: "tickets#updateticket"
  get '/newlocality/:tipo/:precio/:fecha_limite/', to: "localities#newlocality"
  get '/destroyticket/:t', to: "tickets#destroyticket"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/locality.rb
class Locality < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:nombre, :ciudad, :fecha_preventa, :fecha_evento, :localities_id)
    end
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  before_action :set_locality, only: [:show, :edit, :update, :destroy]

  # GET /localities
  # GET /localities.json
  def index
    @localities = Locality.all
  end

  # GET /localities/1
  # GET /localities/1.json
  def show
  end


  def relacion

    @localidadnombrefecha = Event.where("nombre = ?  AND localities_id = ?", params[:nombre],params[:localities_id])
    respond_to do |format|
        format.json { render 'relacion', status: :created, location: @events }
    end
  end


  # GET /localities/new
  def new
    @locality = Locality.new
  end

  # GET /localities/1/edit
  def edit
  end

  # POST /localities
  # POST /localities.json
  def create
    @locality = Locality.new(locality_params)

    respond_to do |format|
      if @locality.save
        format.html { redirect_to @locality, notice: 'Locality was successfully created.' }
        format.json { render :show, status: :created, location: @locality }
      else
        format.html { render :new }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localities/1
  # PATCH/PUT /localities/1.json
  def update
    respond_to do |format|
      if @locality.update(locality_params)
        format.html { redirect_to @locality, notice: 'Locality was successfully updated.' }
        format.json { render :show, status: :ok, location: @locality }
      else
        format.html { render :edit }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localities/1
  # DELETE /localities/1.json
  def destroy
    @locality.destroy
    respond_to do |format|
      format.html { redirect_to localities_url, notice: 'Locality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def newlocality
     @locality = Locality.new(tipo: params[:tipo], precio: params[:precio], fecha_limite: params[:fecha_limite])
          @locality.save
    redirect_to '/localities/'+@locality.id.to_s+'.json'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locality
      @locality = Locality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locality_params
      params.require(:locality).permit(:tipo, :precio, :fecha_limite)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

  #raise @ticket.inspect
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def newticket
     @ticket = Ticket.new(event_id: params[:event_id])
     @ticket.save
    redirect_to '/tickets/'+@ticket.id.to_s+'.json'
  end


  def updateticket
     @ticket = Ticket.update(params[:id_ticket], event_id: params[:event_id ])
     @ticket.save
    redirect_to '/tickets/'+@ticket.id.to_s+'.json'
  end

  def destroyticket
    @ticket = Ticket.find(params[:t])
    @ticket.destroy
   redirect_to '/tickets.json'
      
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:event_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :event_nombre %>
  </div>

  <div class="field">
    <%= form.label :ciudad %>
    <%= form.text_field :ciudad, id: :event_ciudad %>
  </div>

  <div class="field">
    <%= form.label :fecha_preventa %>
    <%= form.date_select :fecha_preventa, id: :event_fecha_preventa %>
  </div>

  <div class="field">
    <%= form.label :fecha_evento %>
    <%= form.date_select :fecha_evento, id: :event_fecha_evento %>
  </div>

<div class="field">
    <%= form.label :localities_id %>
    <%= form.text_field :localities_id, id: :event_fecha_evento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Ciudad</th>
      <th>Fecha preventa</th>
      <th>Fecha evento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.nombre %></td>
        <td><%= event.ciudad %></td>
        <td><%= event.fecha_preventa %></td>
        <td><%= event.fecha_evento %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @event.nombre %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @event.ciudad %>
</p>

<p>
  <strong>Fecha preventa:</strong>
  <%= @event.fecha_preventa %>
</p>

<p>
  <strong>Fecha evento:</strong>
  <%= @event.fecha_evento %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Servicerest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/localities/_form.html.erb
<%= form_with(model: locality, local: true) do |form| %>
  <% if locality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(locality.errors.count, "error") %> prohibited this locality from being saved:</h2>

      <ul>
      <% locality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, id: :locality_tipo %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio, id: :locality_precio %>
  </div>

  <div class="field">
    <%= form.label :fecha_limite %>
    <%= form.date_select :fecha_limite, id: :locality_fecha_limite %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/localities/edit.html.erb
<h1>Editing Locality</h1>

<%= render 'form', locality: @locality %>

<%= link_to 'Show', @locality %> |
<%= link_to 'Back', localities_path %>

app/views/localities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Localities</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Precio</th>
      <th>Fecha limite</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @localities.each do |locality| %>
      <tr>
        <td><%= locality.tipo %></td>
        <td><%= locality.precio %></td>
        <td><%= locality.fecha_limite %></td>
        <td><%= link_to 'Show', locality %></td>
        <td><%= link_to 'Edit', edit_locality_path(locality) %></td>
        <td><%= link_to 'Destroy', locality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Locality', new_locality_path %>

app/views/localities/new.html.erb
<h1>New Locality</h1>

<%= render 'form', locality: @locality %>

<%= link_to 'Back', localities_path %>

app/views/localities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @locality.tipo %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @locality.precio %>
</p>

<p>
  <strong>Fecha limite:</strong>
  <%= @locality.fecha_limite %>
</p>

<%= link_to 'Edit', edit_locality_path(@locality) %> |
<%= link_to 'Back', localities_path %>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id, id: :ticket_event_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.event %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @ticket.event %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>